javascript:
	closure-compiler --js source/javascript/prelude.js --js source/javascript/localisation-selecting.js --js source/javascript/navigation.js --js source/javascript/title-sizing.js --js source/javascript/title-clicking.js --language_in ECMASCRIPT5_STRICT --compilation_level ADVANCED_OPTIMIZATIONS --js_output_file page/index.js --warning_level VERBOSE

css:
	npm install clean-css
	node css-minifier.js
