package testHelper;

import net.mathdoku.plus.enums.CageOperator;
import net.mathdoku.plus.enums.GridType;
import net.mathdoku.plus.enums.PuzzleComplexity;

/**
 * The test grid in this class has been generated with the specified generator
 * version of the app. In case the grid is recreated with the same grid
 * generating parameters as specified by this class, the result should be equal
 * to the grid itself.
 * 
 * All data in the methods below should be kept in sync with the specified
 * version of the generator.
 * 
 * As the data below was generated with hidden operators, this grid can be used
 * with visible and with hidden operator as well.
 */
public class GridCreator2x2 extends GridCreator {
	public static GridCreator2x2 create() {
		return new GridCreator2x2();
	}

	public static GridCreator2x2 createEmpty() {
		GridCreator2x2 gridCreator = new GridCreator2x2();
		gridCreator.setEmptyGrid();
		return gridCreator;
	}

	protected GridCreator2x2() {
		super();
	}

	/**
	 * This code is generated based on a grid which is generated by the app. To
	 * generate the code, use the app in Development Mode. Choose menu option
	 * Development Options -> Generate code for test helper.
	 * 
	 * DO NOT REMOVE THIS TEXT.
	 */
	@Override
	protected long getGameSeed() {
		return 5955006327955777134L;
	}

	protected GridType getGridType() {
		return GridType.GRID_2X2;
	}

	protected boolean getHideOperator() {
		return false;
	}

	protected PuzzleComplexity getPuzzleComplexity() {
		return PuzzleComplexity.VERY_EASY;
	}

	protected int getGeneratorVersionNumber() {
		return 598;
	}

	protected int getMaxCageResult() {
		return 72;
	}

	protected int getMaxCageSize() {
		return 2;
	}

	protected int[] getCorrectValuePerCell() {
		return new int[] {
				// Row 0
				2, 1,
				// Row 1
				1, 2, };
	}

	protected int[] getCageIdPerCell() {
		return new int[] {
				// Row 0
				0, 1,
				// Row 1
				0, 2, };
	}

	protected int[] getResultPerCage() {
		return new int[] {
				// Cage 0
				1,
				// Cage 1
				1,
				// Cage 2
				2, };
	}

	protected CageOperator[] getCageOperatorPerCage() {
		return new CageOperator[] {
				// Cage 0
				CageOperator.SUBTRACT,
				// Cage 1
				CageOperator.NONE,
				// Cage 2
				CageOperator.NONE, };
	}

	@Override
	public String getGridDefinition() {
		return new StringBuilder() //
				// PuzzleComplexity id
				.append("1")
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				// Cage ids for cells on row 0
				.append("0001")
				// Cage ids for cells on row 1
				.append("0002")
				// Definition for cage id 0
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("0,1,2")
				// Definition for cage id 1
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("1,1,0")
				// Definition for cage id 2
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("2,2,0")
				.toString();
	}
}
