package testhelper.gridcreator;

import net.mathdoku.plus.enums.CageOperator;
import net.mathdoku.plus.enums.GridType;
import net.mathdoku.plus.enums.PuzzleComplexity;

public class GridCreator4x4HiddenOperators extends GridCreator4x4 {
	public static GridCreator4x4HiddenOperators create() {
		return new GridCreator4x4HiddenOperators();
	}

	public static GridCreator4x4HiddenOperators createEmpty() {
		GridCreator4x4HiddenOperators gridCreator = new GridCreator4x4HiddenOperators();
		gridCreator.setEmptyGrid();
		return gridCreator;
	}

	public static GridCreator4x4HiddenOperators createEmptyWithSelectedCell(
			int idSelectedCell) {
		GridCreator4x4HiddenOperators gridCreator = new GridCreator4x4HiddenOperators();
		gridCreator.setSelectedCell(idSelectedCell);
		gridCreator.setEmptyGrid();
		return gridCreator;
	}

	protected GridCreator4x4HiddenOperators() {
		super();
	}

	/**
	 * This code is generated based on a grid which is generated by the app. To
	 * generate the code, use the app in Development Mode. Choose menu option
	 * Development Options -> Generate code for test helper.
	 * 
	 * DO NOT REMOVE THIS TEXT.
	 */
	@Override
	protected long getGameSeed() {
		return 8307938949349702277L;
	}

	protected GridType getGridType() {
		return GridType.GRID_4X4;
	}

	protected boolean getHideOperator() {
		return true;
	}

	protected PuzzleComplexity getPuzzleComplexity() {
		return PuzzleComplexity.DIFFICULT;
	}

	protected int getGeneratorVersionNumber() {
		return 598;
	}

	protected int getMaxCageResult() {
		return 9999;
	}

	protected int getMaxCageSize() {
		return 5;
	}

	protected int[] getCorrectValuePerCell() {
		return new int[] {
				// Row 0
				2, 4, 1, 3,
				// Row 1
				1, 3, 4, 2,
				// Row 2
				4, 2, 3, 1,
				// Row 3
				3, 1, 2, 4, };
	}

	protected int[] getCageIdPerCell() {
		return new int[] {
				// Row 0
				1, 0, 2, 2,
				// Row 1
				1, 0, 3, 3,
				// Row 2
				4, 0, 5, 3,
				// Row 3
				4, 0, 0, 6, };
	}

	protected int[] getResultPerCage() {
		return new int[] {
				// Cage 0
				48,
				// Cage 1
				1,
				// Cage 2
				2,
				// Cage 3
				8,
				// Cage 4
				12,
				// Cage 5
				3,
				// Cage 6
				4, };
	}

	protected CageOperator[] getCageOperatorPerCage() {
		return new CageOperator[] {
				// Cage 0
				CageOperator.MULTIPLY,
				// Cage 1
				CageOperator.SUBTRACT,
				// Cage 2
				CageOperator.SUBTRACT,
				// Cage 3
				CageOperator.MULTIPLY,
				// Cage 4
				CageOperator.MULTIPLY,
				// Cage 5
				CageOperator.NONE,
				// Cage 6
				CageOperator.NONE, };
	}

	@Override
	public String getGridDefinition() {
		return new StringBuilder() //
				// PuzzleComplexity id
				.append("4")
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				// Cage ids for cells on row 0
				.append("01000202")
				// Cage ids for cells on row 1
				.append("01000303")
				// Cage ids for cells on row 2
				.append("04000503")
				// Cage ids for cells on row 3
				.append("04000006")
				// Definition for cage id 0
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("0,48,0")
				// Definition for cage id 1
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("1,1,0")
				// Definition for cage id 2
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("2,2,0")
				// Definition for cage id 3
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("3,8,0")
				// Definition for cage id 4
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("4,12,0")
				// Definition for cage id 5
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("5,3,0")
				// Definition for cage id 6
				.append(FIELD_SEPARATOR_GRID_DEFINITION_PART)
				.append("6,4,0")
				.toString();
	}
}
